disabled = false
group_name = group1
bind_addr =
client_bind = true
port = 23000
connect_timeout = 5
network_timeout = 30
heart_beat_interval = 10
stat_report_interval = 10
base_path = /data/fastdfs/storage-meta
max_connections = 1024
buff_size = 256KB
thread_stack_size = 512KB
accept_threads = 1
work_threads = 4
disk_rw_separated = true
disk_reader_threads = 1
disk_writer_threads = 1
sync_min_threads = 1
sync_max_threads = 1
store_path_count = 1
store_path0 = /data/fastdfs/storage
subdir_count_per_path = 256
tracker_server = tracker:22122
allow_hosts = *
log_level = info
check_file_duplicate = false
use_connection_pool = false
check_store_path_mark = true
