disabled = false
bind_addr =
port = 22122
connect_timeout = 5
network_timeout = 30
base_path = /data/fastdfs/tracker
max_connections = 1024
thread_stack_size = 512KB
accept_threads = 1
work_threads = 4
store_lookup = 2
reserved_storage_space = 5%
allow_hosts = *
log_level = info
