CREATE DATABASE IF NOT EXISTS ai_cloud_storage
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_cloud_storage;

CREATE TABLE IF NOT EXISTS user_info (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL UNIQUE,
  nick_name VARCHAR(32) NOT NULL UNIQUE,
  password CHAR(32) NOT NULL,
  salt CHAR(32) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS file_info (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  md5 CHAR(32) NOT NULL UNIQUE,
  storage_key VARCHAR(256) NOT NULL,
  url VARCHAR(512) NOT NULL,
  size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  type VARCHAR(32) NOT NULL DEFAULT '',
  reference_count INT UNSIGNED NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_file_list (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL,
  md5 CHAR(32) NOT NULL,
  file_name VARCHAR(128) NOT NULL,
  shared_status TINYINT NOT NULL DEFAULT 0,
  pv INT UNSIGNED NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_file (user_name, md5),
  CONSTRAINT fk_user_file_user FOREIGN KEY (user_name)
    REFERENCES user_info(user_name) ON DELETE CASCADE,
  CONSTRAINT fk_user_file_info FOREIGN KEY (md5)
    REFERENCES file_info(md5) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS share_file_list (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL,
  md5 CHAR(32) NOT NULL,
  file_name VARCHAR(128) NOT NULL,
  pv INT UNSIGNED NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_shared_user_file (user_name, md5),
  KEY idx_share_created_at (create_time),
  CONSTRAINT fk_share_file_info FOREIGN KEY (md5)
    REFERENCES file_info(md5) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS storage_cleanup_job (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  storage_key VARCHAR(256) NOT NULL,
  reason VARCHAR(64) NOT NULL,
  status ENUM('pending', 'running', 'done') NOT NULL DEFAULT 'pending',
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_error VARCHAR(512) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uq_cleanup_storage_key (storage_key),
  KEY idx_cleanup_status_updated (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
