CREATE DATABASE IF NOT EXISTS ai_cloud_storage
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_cloud_storage;

CREATE TABLE IF NOT EXISTS user_info (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL UNIQUE,
  nick_name VARCHAR(32) NOT NULL UNIQUE,
  password CHAR(32) NOT NULL,
  salt CHAR(32) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
